### ISSUE TITLE
Can't load `test_wiki.json` when training FewRel BaseModel

### ISSUE THREAD

**Issue by hcffffff** [thunlp/Knowledge-Plugin#1]
Really appreciate your work.

However, during training FewRel BERT basemodel, it appears that no `FewRel/test_wiki.json` is given, which is used in `code/config/FewRel/BaseModel/BERT_5way1shot.config` and other configs.

[https://github.com/thunlp/Knowledge-Plugin/blob/master/code/config/FewRel/BaseModel/BERT_5way1shot.config#L17C27-L17C27](url)

Error messages:
```
11/06/2023 15:14:28 - INFO - tools.gpu_tool -   CUDA available: True
11/06/2023 15:14:28 - INFO - __main__ -   Begin to initialize dataset and formatter...
11/06/2023 15:14:30 - INFO - __main__ -   Begin to initialize models...
11/06/2023 15:14:31 - WARNING - __main__ -   Cannot load checkpoint file with error 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
/home/cfh77/anaconda3/envs/apex/lib/python3.9/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
11/06/2023 15:14:33 - INFO - __main__ -   Initialize done.
11/06/2023 15:14:33 - WARNING - tools.train_tool -   Output path exists, check whether need to change a name of model
11/06/2023 15:14:33 - INFO - tools.train_tool -   Training start....
Epoch  Stage  Iterations  Time Usage    Loss    Output Information
Traceback (most recent call last):      398.5589{"micro_f1": 0.273, "micro_precision": 0.273, "micro_recall": 0.273}
  File "/home/cfh77/Documents/Knowledge-Plugin-master/code/run.py", line 129, in <module>
    train(parameters, config)
  File "/home/cfh77/Documents/Knowledge-Plugin-master/code/tools/train_tool.py", line 94, in train
    best_f1 = check(parameters, best_f1, model, current_epoch, optimizer, output_path, config, output_function, global_step)
  File "/home/cfh77/Documents/Knowledge-Plugin-master/code/tools/train_tool.py", line 30, in check
    info = valid(parameters, model, parameters["test_dataset"], current_epoch, config, output_function, mode = "test")[1]
  File "/home/cfh77/Documents/Knowledge-Plugin-master/code/tools/eval_tool.py", line 52, in valid
    data = parameters["Formatter"].process(mode, data)
  File "/home/cfh77/Documents/Knowledge-Plugin-master/code/formatter/FewRel_formatter.py", line 135, in process
    with open(os.path.join(self.data_path, self.config.get("data", "{}_file".format(mode))), "r", encoding = "utf-8") as fin :
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/FewRel/test_wiki.json'
```

How to train FewRel BERT BaseModel? Seems not a file named `test_wiki.json` when training FewRel BERT and related models. How to reach this file or this is a bug?

 Thank you!

**Comment by Zhiyuan-Zeng** [comment]
Hi @hcffffff,

Thanks for reaching out! Actually, `test_wiki.json` has NOT been publicly released. We contacted the authors of [FewRel](https://github.com/thunlp/FewRel) to get this subset.

You could submit your results to the official leaderboard of FewRel. More details are [here](https://github.com/thunlp/Knowledge-Plugin#fewrel-submission).

**Comment by hcffffff** [comment]
OK. Thank you @Zhiyuan-Zeng .
